### ISSUE TITLE
Special characters problem

### ISSUE THREAD

**Issue by cortosdemetraje** [sectsect/wp-tag-order#74] opened 2024-11-16 09:43 UTC
Hi. This plugin has always made my website possible cortosdemetraje.com

I have an important problem, since last update special characters lice spanish accents and "ñ" break the slug of the terms.

The term Óscar Pérez for a cinema director in direccion taxonomy gives this slug https://cortosdemetraje.com/direccion/scar-prez/
when it should be https://cortosdemetraje.com/direccion/oscar-perez/

It´s strange because thousands of my old post did not break the slugs, only since i installed the plugin? 

Could you tell me how to fix it?

Thanks so much for your work.

Best regards.
Alejandro

**Comment by sectsect** [comment] 2024-11-16 12:23
@cortosdemetraje 

Thank you for your feedback.

I tested this and found that the issue was caused by incorrect sanitization.
And this issue has been resolved.

Released in [v3.8.2](https://github.com/sectsect/wp-tag-order/releases/tag/v3.8.2).
Try it out.

**Comment by cortosdemetraje** [comment] 2024-11-16 19:25
Incredible! You can´t imagine how much time have spent trying to fix it.

Muchísimas Gracias!!!

Thx a lot!!!

**Comment by sectsect** [comment] 2024-11-16 22:49
@cortosdemetraje 
Your feedback has helped make this plugin even better.
Thank you.

**Closed by sectsect** 2024-11-16 22:49 UTC
