### ISSUE TITLE
I can´t add or edit post

### ISSUE THREAD

**Issue by cortosdemetraje** [sectsect/wp-tag-order#92] opened 2024-12-23 19:54 UTC
Good evening.

Since last update (not today, but also), if i activate the plugin i cannot add new posts or edit old post. When i try, appears this message: "No enabled taxonomies found for post type "post".

It works when i desactivate de plugin.

Merry christmas and thx for all!

**Comment by sectsect** [comment] 2024-12-24 03:16
@cortosdemetraje 

Thank you for reporting this issue, and Merry Christmas! 🎄

This problem was caused by excessive error handling that unintentionally affected post types not using this plugin. It has been fixed in version [v3.11.6](https://github.com/sectsect/wp-tag-order/releases/tag/v3.11.6).  

Please update to the latest version, and let us know if the issue persists.

Thank you for your patience and support! 🙏

**Closed** 2024-12-24 03:16 UTC

**Comment by cortosdemetraje** [comment] 2024-12-24 07:40
It worked. Thx a lot!!
