### ISSUE TITLE
Minor issue with single quotation marks

### ISSUE THREAD

**Issue by s-p-a-r-k-z** [sectsect/wp-tag-order#7] opened 2019-10-22 10:47 UTC
Hi,
Thanks for a brilliant plugin, which fixes a huge lack in WP native !
I noticed that if the tag added contains a single quote (ex. L'amour), wp-tag-order won't work  properly. 
I guess it's just about escaping the string before sending it but I couldn't find where to do this. 
I'd be grateful if you could sort this issue.
Thanks a lot

**Comment by sectsect** [comment] 2019-10-22 13:17
@s-p-a-r-k-z 

Thanks for your feedback.

The problem was caused by unnecessary escaping of the input values.
This problem is solved.

Released in [v1.1.4](https://github.com/sectsect/wp-tag-order/releases/tag/v1.1.4)!

**Closed by sectsect** 2019-10-22 13:17 UTC
